title: Cathax's Reports
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://doltegg.github.io
baseurl: /cathax
paginate_path: "/page:num/"
permalink: /:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: brianmaierjr
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: r90323011@ntu.edu.tw

google_analytics: "UA-58263416-1"
